<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Formal Public Identifier (PRODID)
    |--------------------------------------------------------------------------
    |
    | The iCalendar specification (RFC 5545) requires a "PRODID" property for
    | every "VCALENDAR" component. The value "PRODID" should take is set here
    | and must be a globally unique FPI value, as defined in ISO.9070.1991.
    |
     */
    'fpi' => env('ICS_API', '-//Phoosha//Dienstplan//EN'),

    /*
    |--------------------------------------------------------------------------
    | Event Organizer
    |--------------------------------------------------------------------------
    |
    | This will be set as the "ORGANIZER" property on iCalendar objects
    | generated by the application. It should be a valid email address prefixed
    | with "mailto:" as the method.
    |
     */
    'organizer' => env('ICS_ORGANIZER', 'mailto:hello@example.com'),

    /*
    |--------------------------------------------------------------------------
    | Event Summary
    |--------------------------------------------------------------------------
    |
    | This is the value set for the "SUMMARY" property of iCalendar "VEVENT"
    | components. This is commonly displayed as the title of the event by
    | calendar application and can be set to any string of textual characters.
    |
     */
    'summary' => env('ICS_SUMMARY', 'Dienst FRS'),

    /*
    |--------------------------------------------------------------------------
    | Event Location
    |--------------------------------------------------------------------------
    |
    | This is the value set for the "LOCATION" property of iCalendar "VEVENT"
    | components. It can be set to any string of textual characters and may
    | contain the string ":slot", which is dynamically replaced by the slot
    | (i.e. vehicle) of the duty the event is generated from.
    |
     */
    'location' => env('ICS_LOCATION', ':slot, Musterheim'),

    /*
    |--------------------------------------------------------------------------
    | Recommended (Minimal) Refresh Interval
    |--------------------------------------------------------------------------
    |
    | This is the value set for the "REFRESH-INTERVAL" property of an iCalendar
    | "VCALENDAR" component. It must be set to a valid "DURATION" value as
    | specified by section 3.3.6 of RFC 5545, but WITHOUT the "P" prefix.
    |
     */
    'refresh_interval' => env('ICS_REFRESH_INTERVAL', 'T15M'),

    /*
    |--------------------------------------------------------------------------
    | Calendar Color
    |--------------------------------------------------------------------------
    |
    | This is the value set for the "COLOR" property of an iCalendar "VCALENDAR"
    | component. It is commonly used by calendar application as the background
    | color for events and must be set to a valid CSS color value. If it is set
    | to an empty value, the "COLOR" property is omitted from the resulting
    | iCalendar object.
    |
     */
    'color' => env('ICS_COLOR', 'firebrick'),

];
